=== RuedigerLunde/sql-trainer/sql-trainer/sql-trainer-config/xml/exercise-set.dtd
<!-- Format for sql exercises set documents. Author: R. Lunde -->

<!ELEMENT exercise-set (intro, exercise*)>
<!ATTLIST exercise-set course CDATA #REQUIRED>
<!ATTLIST exercise-set lecturer CDATA #REQUIRED>
<!ATTLIST exercise-set id CDATA #REQUIRED>
<!ATTLIST exercise-set db CDATA #IMPLIED>
<!ATTLIST exercise-set editor CDATA #IMPLIED>
<!ATTLIST exercise-set lastEdit CDATA #IMPLIED>
<!ATTLIST exercise-set checksum CDATA #IMPLIED>
<!ATTLIST exercise-set hasha CDATA #IMPLIED>
<!ATTLIST exercise-set hashs CDATA #IMPLIED>
<!ATTLIST exercise-set passwd CDATA #IMPLIED>
<!ELEMENT intro (#PCDATA|p|b|i|tt|ul|pre)*>
<!ELEMENT exercise (question, answer?, solution?)>
<!ATTLIST exercise id CDATA #REQUIRED>
<!ATTLIST exercise type CDATA #IMPLIED>
<!ATTLIST exercise theme CDATA #IMPLIED>
<!ELEMENT question (#PCDATA|p|b|i|tt|ul|pre)*>
<!ELEMENT answer (#PCDATA)>
<!ELEMENT solution (#PCDATA)>
<!ATTLIST solution test CDATA #IMPLIED>
<!ELEMENT p (#PCDATA|b|i|pre)*>
<!ELEMENT b (#PCDATA|i|tt)*>
<!ELEMENT i (#PCDATA|b|tt)*>
<!ELEMENT tt (#PCDATA|b|i)*>
<!ELEMENT ul (li*)>
<!ELEMENT li (#PCDATA|p|b|i|tt|ul)*>
<!ELEMENT pre (#PCDATA)>

=== RuedigerLunde/sql-trainer/sql-trainer/sql-trainer-config/exercises/Uebungsblatt-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE exercise-set SYSTEM "exercise-set.dtd">
<exercise-set course="Einführung in Datenbanken (DABAS-MD2)" db="WhiskyDB" id="0" lecturer="Prof. Dr. R. Lunde" passwd=""><intro>Nachdem Sie das Dokument ToolUebersicht.pdf gelesen haben und den SQLTrainer erfolgreich
installiert haben, begleitet Sie dieses Übungsblatt durch die ersten Schritte bei der
Anwendung des Werkzeugs. Jedes Übungsblatt liegt sowohl als HTML-Datei zur Anzeige
im Web-Browser als auch als XML-Datei vor. Die XML-Version kann über [File][Load Exercises] vom
SQLTrainer eingelesen werden, was Sie - wenn nicht bereits geschehen - nun ausprobieren sollten.
Der SQLTrainer erfragt dabei Ihren Namen um diesen zusammen mit den von Ihnen eingegebenen
Antworten abspeichern zu können.
<p>Mit dem Knopf [Next Exercise] oder [F2] gelangen Sie zur ersten Aufgabe.</p>
	</intro><exercise id="1a" theme="SQLTrainer"><question>
Es gibt verschiedene Aufgabentypen. SQL-Aufgaben erkennen Sie daran, dass der [Execute]-Knopf
aktiv wird. Machen Sie sich aber zunächst mit den Bedienelementen des SQLTrainers vertraut.
Auf der Werkzeugleiste finden Sie neben der Aufgabennavigation eine Datenbank-Auswahl. Zur
gewählten Datenbank erscheinen in den Tabs [DB Schema] und [DB Description] nützliche
Informationen. Die Größe der Anzeigefelder können Sie per Maus-Drag auf die entsprechenden
Trennlinien anpassen. Weiter mit [F2].
    </question></exercise><exercise id="1b" theme="SQLTrainer" type="sql"><question>
Testen Sie nun die Eingabe einer SQL-Anweisung. Tippen Sie dazu im Antwortfeld die folgende
Anweisung ein: <pre>select * from Whiskies</pre>
Stellen Sie sicher, dass die WhiskyDB ausgwählt ist, und drücken Sie [Execute]. Bestätigen
Sie die voreingestellten Verbindungsdaten. Wenn die Verbindung zum Server steht erscheint
im [Results]-Tab die Tabelle, die der Server als Antwort zurück meldet. Andernfalls müssen Sie
sich mit der Fehlermeldung im unteren Bereich des Fensters auseinandersetzen.
Der Fehleranzeigebereich verfügt über ein Kontextmenü
und kann durch Wahl von [Clear] wieder geleert und verdeckt werden.

<p>Sie können
 auch mehrere Select-Anweisungen eingeben und dann durch Markieren entscheiden,
welche Anweisung ausgeführt werden soll.</p>
		</question><solution>select * from Whiskies

-- select * from WhiskyBeschreibungen</solution></exercise><exercise id="1c" theme="SQLTrainer" type="sql"><question>Versuchen Sie, eine Anfrage zu formulieren, die die Anzahl der in der Datenbank erfassten
Whiskies ermittelt und testen Sie die Anfrage mit [Execute]. Auf Wunsch generiert Ihnen
das System auch eine Rückmeldung über die inhaltliche Richtigkeit Ihrer Lösung
(Knopf [Feedback]). Natürlich haben nicht alle Aufgaben ein eindeutiges Ergebnis. Deshalb
kann es auch vollkommen richtige Lösungen geben, die nicht mit einem Smiley belohnt
werden.

<p>Zugegeben, die Musterlösung ist in diesem Fall  nur einen Tab entfernt ([Solution]). Wer knobelt
da schon gerne lange herum. Deshalb wird bei den folgenden Aufgabenblättern der Zugang
zur Lösung mit einem Passwort gesperrt sein. Sie können dieses Feature ausprobieren,
wenn Sie [Exercise][Lock Solutions] aktivieren.</p></question><solution>select count(*) as Anzahl
from Whiskies</solution></exercise><exercise id="1d" theme="SQLTrainer"><question>
Ihre Arbeitsergebnisse können Sie jeder Zeit mit [File][Save Exercises] abspeichern.
Neben einer entsprechenden XML-Datei, die Sie erneut laden und weiter bearbeiten können, wird
auch eine HTML-Version erzeugt und im Tab [HTML Export] angezeigt. Beachten Sie, dass bei
Verwendung des voreingestellen Namens das ursprüngliche Übungsblatt überschrieben wird.
Tipp: Fügen Sie in den Namen Ihre Initialen ein, z.B. Uebungsblatt-0.RLu.xml.
		</question></exercise><exercise id="1e" theme="SQLTrainer"><question>Schließlich können Sie mit dem SQLTrainer auch selbst Aufgabenblätter entwerfen. Dazu aktivieren
Sie [View][Enable Authoring]. Nun können mit [File][New]  neue Arbeitsblätter angelegt werden und mit
den Funktionen im [Authoring]-Menü editiert werden (letzteres gilt natürlich nur für nicht gesperrte
Aufgabenblätter).

<p>Jetzt kennen Sie die wichtigsten Handgriffe und können beginnen, Ihre ersten
SQL-Aufgaben zu lösen.</p></question></exercise><exercise id="2a" theme="einfache Select-Anweisungen" type="sql"><question>
Erzeugen Sie eine Liste aller Whisky-Marken ohne Wiederholungen, aufsteigend sortiert.
		</question><solution>select distinct WMarke
from Whiskies
order by WMarke</solution></exercise><exercise id="2b" theme="einfache Select-Anweisungen" type="sql"><question>
Erzeugen Sie eine Liste aller Whiskies, charaktierisiert durch Marke und Alter,
die mindestens 12 Jahre alt sind, primär nach Alter absteigend, dann nach Marke aufsteigend sortiert.
		</question><solution>select WMarke, WAlter
from Whiskies
where WAlter &gt;= 12
order by WAlter desc, WMarke</solution></exercise><exercise id="2c" theme="einfache Select-Anweisungen" type="sql"><question>
Erzeugen Sie eine Liste aller Whisky-Marken, die den Buchstaben 'i' enthalten, ohne Wiederholungen.
		</question><solution>select distinct WMarke
from Whiskies
where WMarke like '%i%'</solution></exercise><exercise id="3a" theme="einfache Select-Anweisungen" type="sql"><question>
Wie viele Whiskies sind für die Region Islay Malt erfasst?
		 </question><solution>select count(WNr) as 'Anzahl Whiskies'
from Whiskies
where Region='Islay Malt'</solution></exercise><exercise id="3b" theme="einfache Select-Anweisungen" type="sql"><question>
Wie viele Whisky-Marken sind für die Region Islay Malt erfasst?
		</question><solution>select count(distinct WMarke) as 'Anzahl Whiskies'
from Whiskies
where Region='Islay Malt'</solution></exercise><exercise id="3c" theme="einfache Select-Anweisungen" type="sql"><question>
Wie alt ist der älteste Whisky in der Datenbank?
		</question><solution>select max(WAlter) as 'Maximales Alter'
from Whiskies</solution></exercise></exercise-set>
